# Generated by Django 2.0.1 on 2018-01-08 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ctype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.CourseType'),
            preserve_default=False,
        ),
    ]
